### ISSUE TITLE
Revamp the landing page to reflect whisper key instead of rankproof

### ISSUE THREAD

**Issue by anandcsingh** [anandcsingh/whisper-key#24]
Content 
https://github.com/anandcsingh/whisper-key#readme

https://docs.google.com/document/d/1-_CKLe2hcFCJK4MZ4_NzXZESrOYDL9OzVQhqLkvpVTY/edit#heading=h.anq031y8n0hf

**Comment by pteelucksingh** [comment]
@anandcsingh review some of this content I added pls
